Repository P4-Games/ChatterPay-Backend, pull requests merged in 2024-10, with the labels that each got.

#69 merge feature/nft-id-string into develop
  src/api/nftRoutes.ts
  src/config/database.ts
  src/controllers/nftController.ts
  src/controllers/replyController.ts
  src/controllers/swapController.ts
  src/models/blockchain.ts
  src/models/nft.ts
  src/services/predictWalletService.ts
  src/services/walletService.ts
  src/utils/dynamicGas.ts
Labels: enhancement

#70 merge fix/types into develop
  src/controllers/nftController.ts
  src/controllers/replyController.ts
  src/services/predictWalletService.ts
  src/services/walletService.ts
Labels: bug

#73 merge fix/types-2 into develop
  src/controllers/replyController.ts
Labels: bug

#75 merge fix/typo into develop
  src/controllers/replyController.ts
Labels: bug

#76 merge hotfix/open-sea-url into main
  src/controllers/replyController.ts
Labels: bug

#80 merge feature/20241001 into develop
  bun.lockb
  cloudbuild.yaml
  package.json
  scripts/docker-build.sh
  src/services/transactionsService.ts
Labels: documentation, enhancement

#82 merge fix/buid-env into develop
  Dockerfile
  cloudbuild.yaml
Labels: bug

#83 merge develop into main
  Dockerfile
  cloudbuild.yaml
Labels: bug, enhancement

#91 merge feature/20241002 into develop
  .env.example
  Dockerfile
  cloudbuild.yaml
  scripts/docker-build.sh
  src/api/nftRoutes.ts
  src/config/database.ts
  src/constants/contracts.ts
  src/controllers/nftController.ts
  src/utils/uploadServices.ts
Labels: enhancement

#95 merge feature/2024103 into develop
  src/constants/contracts.ts
  src/controllers/nftController.ts
  src/controllers/replyController.ts
  src/controllers/transactionController.ts
  src/models/nft.ts
  src/services/networkService.ts
  src/services/predictWalletService.ts
  src/services/transactionsService.ts
  src/services/walletService.ts
  src/utils/uploadServices.ts
Labels: enhancement

#97 merge feature/20241003-2
  src/controllers/nftController.ts
  src/models/nft.ts
Labels: enhancement

#99 merge feature/20241003-3 into develop
  src/controllers/nftController.ts
  src/models/nft.ts
Labels: enhancement

#100 Move use of environment variables to a constants file
  src/config/database.ts
  src/config/server.ts
  src/constants/contracts.ts
  src/controllers/balanceController.ts
  src/controllers/nftController.ts
  src/controllers/swapController.ts
  src/controllers/tokenController.ts
  src/services/predictWalletService.ts
  src/services/walletService.ts
  src/utils/uploadServices.ts
  src/utils/web3_config.ts
Labels: enhancement

#103 Refactor/redo externalize environment
  src/config/database.ts
  src/config/server.ts
  src/constants/contracts.ts
  src/constants/environment.ts
  src/controllers/balanceController.ts
  src/controllers/nftController.ts
  src/controllers/replyController.ts
  src/controllers/swapController.ts
  src/controllers/tokenController.ts
  src/models/nft.ts
  src/services/predictWalletService.ts
  src/services/walletService.ts
  src/utils/uploadServices.ts
  src/utils/web3_config.ts
Labels: enhancement

#105 Revert "Feature/externalize abis"
  .env.example
  Dockerfile
  bun.lockb
  cloudbuild.yaml
  package.json
  src/constants/environment.ts
  src/controllers/swapController.ts
  src/services/bucketService.ts
  src/services/predictWalletService.ts
  src/services/walletService.ts
  src/types/ethers-contracts/ChatterPay.ts
  src/types/ethers-contracts/ChatterPayWalletFactory.ts
  src/types/ethers-contracts/common.ts
  src/types/ethers-contracts/factories/ChatterPayWalletFactory__factory.ts
  src/types/ethers-contracts/factories/ChatterPay__factory.ts
  src/types/ethers-contracts/index.ts
  src/utils/chatterPayABI.json
  src/utils/entryPoint.json
Labels: invalid

#106 merge 20241004-1 into develop
  src/config/database.ts
  src/config/swagger.ts
  src/constants/environment.ts
  src/controllers/nftController.ts
  src/utils/uploadServices.ts
Labels: enhancement

#113 merge feature/20241004-3 into develop
  .env.example
  Dockerfile
  bun.lockb
  cloudbuild.yaml
  package.json
  scripts/docker-build.sh
  src/config/server.ts
  src/constants/contracts.ts
  src/constants/environment.ts
  src/controllers/nftController.ts
Labels: enhancement

#117 Endpoint to detect, notify, and save external deposits to ChatterPay addresses
  bun.lockb
  package.json
  scripts/initLastProcessedBlock.ts
  src/api/balanceRoutes.ts
  src/constants/environment.ts
  src/controllers/balanceController.ts
  src/controllers/replyController.ts
  src/models/lastProcessedBlock.ts
  src/services/externalDepositsService.ts
  tsconfig.json
Labels: enhancement

#115 Fixed Token Authentication - (Chatizalo / Front)
  Dockerfile
  bun.lockb
  cloudbuild.yaml
  package.json
  scripts/docker-build.sh
  src/config/server.ts
  src/config/token.ts
  src/constants/environment.ts
  src/middleware/authMiddleware.ts
  src/utils/generateTokens.ts
Labels: enhancement

#136 deploy fix/20241027 into develop
  .env.example
  Dockerfile
  cloudbuild.yaml
  scripts/docker-build.sh
  src/middleware/authMiddleware.ts
Labels: bug, enhancement

#137 merge feat/improve-dockerfile into develop
  cloudbuild.yaml
Labels: enhancement

#138 merge fix/build into develop
  Dockerfile
Labels: bug

#140 merge feature/example-env-update into develop
  .env.example
Labels: documentation

#141 merge release/20241027-2 into main
  .env.example
Labels: documentation
