Repository P4-Games/ChatterPay-Backend, pull requests merged in 2025-06, with the labels that each got.

#509 merge feature/508-add-tag-logs into develop
  src/controllers/nftController.ts
  src/controllers/swapController.ts
  src/controllers/transactionController.ts
  src/controllers/walletController.ts
  src/controllers/withdrawController.ts
  src/services/swapService.ts
  src/services/transferService.ts
  src/services/web3/userOperationService.ts
Labels: enhancement

#510 Fix: Deposits notification
  src/helpers/formatHelper.ts
  src/services/externalDepositsService.ts
  src/services/mongo/mongoTokenService.ts
  src/services/notificationService.ts
Labels: bug

#512 merge feature/502-update-user-name into develop
  scripts/update_users_name.ts
Labels: enhancement

#513 merge release/20250605 into main
  scripts/update_users_name.ts
  src/controllers/nftController.ts
  src/controllers/swapController.ts
  src/controllers/transactionController.ts
  src/controllers/walletController.ts
  src/controllers/withdrawController.ts
  src/helpers/formatHelper.ts
  src/models/notificationModel.ts
  src/models/templateModel.ts
  src/services/blockchainService.ts
  src/services/externalDepositsService.ts
  src/services/mongo/mongoNotificationServices.ts
  src/services/mongo/mongoTokenService.ts
  src/services/notificationService.ts
  src/services/swapService.ts
  src/services/transferService.ts
  src/services/web3/userOperationService.ts
  test/models/templateModel.test.ts
Labels: enhancement

#519 merge fix/fee-transfer-abis into develop
  src/services/web3/abis/ChatterPay.sol/ChatterPay.json
  src/services/web3/abis/ChatterPay.sol/IERC20Extended.json
  src/services/web3/abis/ChatterPayNFT.sol/ChatterPayNFT.json
  src/services/web3/abis/ChatterPayPaymaster.sol/ChatterPayPaymaster.json
  src/services/web3/abis/ChatterPayWalletFactory.sol/ChatterPayWalletFactory.json
  src/services/web3/abis/ChatterPayWalletFactory.sol/IChatterPayWalletFactory.json
  src/services/web3/abis/ChatterPayWalletProxy.sol/ChatterPayWalletProxy.json
Labels: enhancement

#522 merge feature/520-avoid-redundant-proxy-computation into develop
  src/controllers/swapController.ts
  src/controllers/transactionController.ts
  src/services/blockchainService.ts
  src/services/transferService.ts
  src/services/web3/contractSetupService.ts
  src/services/web3/userOperationService.ts
Labels: enhancement

#523 merge feature/521-track-factory-and-proxy-implementation into develop
  src/controllers/nftController.ts
  src/controllers/transactionController.ts
  src/controllers/walletController.ts
  src/models/userModel.ts
  src/services/userService.ts
  test/models/userModel.test.ts
Labels: enhancement

#530 [feat] :sparkles: add wbtc support in balance service (#529)
  src/services/balanceService.ts
Labels: enhancement

#544 [refactor] :recycle: add detailed logging to wraRpc (#536)
  src/services/predictWalletService.ts
  src/services/web3/bundlerService.ts
  src/services/web3/rpc/rpcService.ts
  src/services/web3/userOperationService.ts
Labels: enhancement

#545 merge feature/542-rate-limit-env into develop
  Dockerfile
  cloudbuild.yaml
  example_env
  scripts/docker-build.sh
  src/config/constants.ts
  src/config/plugins/rateLimitPlugin.ts
Labels: enhancement

#551 merge Feature/549-optional-notif-in-external-deposits into develop
  src/controllers/balanceController.ts
  src/services/externalDepositsService.ts
Labels: bug, enhancement

#557 merge feature/556-display-symbol-in-get-balance into develop
  src/models/tokenModel.ts
  src/services/balanceService.ts
  src/types/commonType.ts
  test/models/tokenModel.test.ts
Labels: enhancement

#559 merge feature/558-display-symbol-tranfer-and-swap into develop
  src/controllers/swapController.ts
  src/controllers/transactionController.ts
  src/services/balanceService.ts
  src/services/blockchainService.ts
  src/services/swapService.ts
  src/types/commonType.ts
Labels: enhancement

#560 merge fix/558-swap-output-symbol into develop
  src/services/blockchainService.ts
Labels: bug

#561 merge release/20250619 into develop
  Dockerfile
  cloudbuild.yaml
  example_env
  scripts/docker-build.sh
  scripts/subscribe_wallets_to_push_channel.ts
  scripts/swap_debug/adjust_pool.ts
  scripts/swap_debug/create_proxy.ts
  scripts/swap_debug/run_all.sh
  scripts/update_users_name.ts
  scripts/update_users_wallet_eoa.ts
  src/api/blockchainRoutes.ts
  src/api/supportRoutes.ts
  src/api/walletRoutes.ts
  src/config/constants.ts
  src/config/middlewares/torMiddleware.ts
  src/config/plugins/rateLimitPlugin.ts
  src/controllers/ImageController.ts
  src/controllers/balanceController.ts
  src/controllers/blockchainController.ts
  src/controllers/nftController.ts
  src/controllers/rampController.ts
  src/controllers/supportController.ts
  src/controllers/swapController.ts
  src/controllers/tokenController.ts
  src/controllers/transactionController.ts
  src/controllers/walletController.ts
  src/controllers/withdrawController.ts
  src/helpers/SecurityHelper.ts
  src/models/blockchainModel.ts
  src/models/countries.ts
  src/models/templateModel.ts
  src/models/tokenModel.ts
  src/models/userModel.ts
  src/services/balanceService.ts
  src/services/blockchainService.ts
  src/services/cache/cacheService.ts
  src/services/coingecko/coingeckoService.ts
  src/services/externalDepositsService.ts
  src/services/mongo/mongoCountryService.ts
  src/services/mongo/mongoUserService.ts
  src/services/notificationService.ts
  src/services/predictWalletService.ts
  src/services/swapService.ts
  src/services/userService.ts
  src/services/walletService.ts
  src/services/web3/abiService.ts
  src/services/web3/bundlerService.ts
  src/services/web3/contractSetupService.ts
  src/services/web3/gasService.ts
  src/services/web3/paymasterService.ts
  src/services/web3/rpc/rpcQueue.ts
  src/services/web3/rpc/rpcService.ts
  src/services/web3/userOperationService.ts
  src/types/commonType.ts
  test/models/tokenModel.test.ts
  test/models/userModel.test.ts
Labels: bug, enhancement

#565 merge release/20250619-2 into main
  src/services/externalDepositsService.ts
Labels: bug

#567 merge feature/566-quick-response-create-wallet into develop
  src/api/walletRoutes.ts
  src/controllers/walletController.ts
  src/models/templateModel.ts
  src/services/chatizalo/chatizaloService.ts
  src/services/notificationService.ts
  src/services/userService.ts
  test/models/templateModel.test.ts
Labels: enhancement
