Repository P4-Games/ChatterPay-Backend, pull requests merged in 2025-03, with the labels that each got.

#394 merge feature/receipt-time-info into develop
  src/services/web3/userOpExecutorService.ts
Labels: enhancement

#396 merge feature/adjust-paymaster-min-values into develop
  src/config/constants.ts
Labels: enhancement

#399 merge feature/env-variables-to-bdd into develop
  Dockerfile
  cloudbuild.yaml
  example_env
  scripts/docker-build.sh
  src/config/constants.ts
  src/controllers/balanceController.ts
  src/controllers/nftController.ts
  src/controllers/tokenController.ts
  src/controllers/transactionController.ts
  src/controllers/walletController.ts
  src/models/blockchainModel.ts
  src/services/balanceService.ts
  src/services/blockchainService.ts
  src/services/mongo/mongoBlockchainService.ts
  src/services/predictWalletService.ts
  src/services/swapService.ts
  src/services/transferService.ts
  src/services/web3/contractSetupService.ts
  src/services/web3/paymasterService.ts
  src/services/web3/userOperationService.ts
  test/models/blockchainModel.test.ts
  test/models/lastProcessedBlockModel.test.ts
Labels: enhancement

#400 merge fix/20250803 into develop
  src/config/constants.ts
  src/models/blockchainModel.ts
  test/models/blockchainModel.test.ts
  test/models/lastProcessedBlockModel.test.ts
Labels: bug

#402 merge fix/harcoded-blockchain-name into develop
  src/services/predictWalletService.ts
Labels: enhancement

#407 merge feature/dynamic-gas into develop
  .doc/development/documentation-links.md
  src/controllers/swapController.ts
  src/controllers/transactionController.ts
  src/helpers/paymasterHelper.ts
  src/models/blockchainModel.ts
  src/services/predictWalletService.ts
  src/services/swapService.ts
  src/services/transferService.ts
  src/services/web3/bundlerService.ts
  src/services/web3/gasService.ts
  src/services/web3/userOpExecutorService.ts
  src/services/web3/userOperationService.ts
  src/types/commonType.ts
  test/models/blockchainModel.test.ts
  test/models/lastProcessedBlockModel.test.ts
Labels: bug, enhancement

#411 merge feature/improve-send-user-op into develop
  .doc/development/documentation-links.md
  src/models/blockchainModel.ts
  src/services/swapService.ts
  src/services/transferService.ts
  src/services/web3/gasService.ts
  src/services/web3/userOperationService.ts
  test/models/blockchainModel.test.ts
  test/models/lastProcessedBlockModel.test.ts
Labels: enhancement

#416 merge feature/20259313 into develop
  src/controllers/nftController.ts
  src/controllers/swapController.ts
  src/controllers/transactionController.ts
  src/services/notificationService.ts
Labels: enhancement

#417 Feat: Testnet pool adjustment based on ether price, removed price protection on testnet
  scripts/swap_debug/adjust_pool.ts
  scripts/swap_debug/swap_tokens.ts
  src/services/coingecko/coingeckoService.ts
  src/services/swapService.ts
Labels: documentation, enhancement

#420 merge fix/generic-estimated-gas into develop
  src/config/middlewares/originMiddleware.ts
  src/controllers/nftController.ts
  src/helpers/paymasterHelper.ts
  src/services/predictWalletService.ts
  src/services/web3/gasService.ts
Labels: bug

#421 Feat: adapt paymaster validation
  src/controllers/tokenController.ts
  src/helpers/paymasterHelper.ts
  src/services/web3/abis/ChatterPay.sol/ChatterPay.json
  src/services/web3/abis/ChatterPay.sol/ChatterPayStorage.json
  src/services/web3/abis/ChatterPay.sol/IERC20Extended.json
  src/services/web3/abis/ChatterPayNFT.sol/ChatterPayNFT.json
  src/services/web3/abis/ChatterPayPaymaster.sol/ChatterPayPaymaster.json
  src/services/web3/abis/ChatterPayVault.sol/ChatterPayVault.json
  src/services/web3/abis/ChatterPayWalletFactory.sol/ChatterPayWalletFactory.json
  src/services/web3/abis/ChatterPayWalletFactory.sol/IChatterPayWalletFactory.json
  src/services/web3/abis/ChatterPayWalletProxy.sol/ChatterPayWalletProxy.json
  src/services/web3/abis/ERC20.sol/ERC20.json
  src/services/web3/abis/EntryPoint.sol/EntryPoint.json
Labels: enhancement

#423 merge feature/update-abis into develop
  src/services/web3/abis/ChatterPay.sol/ChatterPay.json
  src/services/web3/abis/ChatterPay.sol/ChatterPayStorage.json
  src/services/web3/abis/ChatterPay.sol/IERC20Extended.json
  src/services/web3/abis/ChatterPayNFT.sol/ChatterPayNFT.json
  src/services/web3/abis/ChatterPayPaymaster.sol/ChatterPayPaymaster.json
  src/services/web3/abis/ChatterPayVault.sol/ChatterPayVault.json
  src/services/web3/abis/ChatterPayWalletFactory.sol/ChatterPayWalletFactory.json
  src/services/web3/abis/ChatterPayWalletFactory.sol/IChatterPayWalletFactory.json
  src/services/web3/abis/ChatterPayWalletProxy.sol/ChatterPayWalletProxy.json
Labels: enhancement

#426 merge feature/wallet-not-found into develop
  src/controllers/balanceController.ts
  src/controllers/nftController.ts
  src/controllers/swapController.ts
  src/controllers/transactionController.ts
Labels: enhancement

#428 Feature/operation limits
  src/api/supportRoutes.ts
  src/controllers/nftController.ts
  src/controllers/supportController.ts
  src/controllers/swapController.ts
  src/controllers/transactionController.ts
  src/models/blockchainModel.ts
  src/models/templateModel.ts
  src/models/userModel.ts
  src/services/blockchainService.ts
  src/services/mongo/mongoUserService.ts
  src/services/notificationService.ts
  src/services/userService.ts
  test/models/blockchainModel.test.ts
  test/models/lastProcessedBlockModel.test.ts
  test/models/templateModel.test.ts
Labels: enhancement
